// ENUM E' UN ENTITA' SOFTWARE CHE SERVE A RAGGRUPPARE COSTANTI DEFINITE COME COLORI-IMMAGINI-ECC E POTERLE IMPORTARE
// DOVE MI SERVONO
// DA UN ENUM DEFINENDO LA VARIABILE DI ISTANZA POTRA' ACCEDERE A TUTTE LE SUE COSTANTI

enum Color {
  Rosso = 4,
  Verde,
  Blu,
  Rosa,
  Bianco,
}

let colors: Color = Color.Blu;
console.log(colors);